# Docker Compose - Cloud SQL Only Configuration
# Local MySQL removed - using Cloud SQL at 34.173.128.29

services:
  oa-server:
    build:
      context: ./apps/oa-server-deploy
      dockerfile: Dockerfile
    container_name: aiaccounting-oa-server
    ports:
      - "8080:8080"
    environment:
      # OA Server now connects directly to Cloud SQL
      - DB_HOST=34.173.128.29
      - DB_USER=cashflowadmin
      - DB_NAME=cashflowdb
      - DB_PASSWORD=C@shflow132
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
