name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd apps/bff && npm ci
        cd ../web && npm ci
    
    - name: Typecheck
      run: |
        cd apps/bff && npx tsc --noEmit
        cd ../web && npx tsc --noEmit
    
    - name: Lint
      run: |
        cd apps/web && npm run lint
    
    - name: Test BFF
      env:
        BFF_DATABASE_URL: mysql://root:root@localhost:3306/test_db
        OA_BASE_URL: https://oa-server.example.com
        JWT_SECRET: test-secret-key
      run: |
        cd apps/bff && npm test
    
    - name: Build
      run: |
        cd apps/bff && npm run build
        cd ../web && npm run build
